// Data from https://www.lethe.xyz/mtg/collation/2ed.html
const limitedRareSheet = [
    "winter orb",
    "nightmare",
    "jade monolith",
    "manabarbs",
    "mox emerald",
    "elvish archers",
    "sunglasses of urza",
    "animate wall",
    "tundra",
    "sleight of mind",
    "chaos orb",
    //
    "lifelace",
    "savannah",
    "righteousness",
    "ancestral recall",
    "black lotus",
    "bad moon",
    "mox sapphire",
    "raging river",
    "fungusaur",
    "northern paladin",
    "magical hack",
    //
    "cockatrice",
    "mox ruby",
    "blaze of glory",
    "disrupting scepter",
    "lord of the pit",
    "mana flare",
    "taiga",
    "natural selection",
    "crusade",
    "mana short",
    "birds of paradise",
    //
    "cyclopean tomb",
    "contract from below",
    "badlands",
    "granite gargoyle",
    "mox pearl",
    "timber wolves",
    "meekstone",
    "savannah lions",
    "vesuvan doppelganger",
    "word of command",
    "forcefield",
    //
    "chaoslace",
    "the hive",
    "lord of atlantis",
    "warp artifact",
    "roc of kher ridges",
    "force of nature",
    "farmstead",
    "mahamoti djinn",
    "volcanic island",
    "volcanic eruption",
    "island",
    //
    "lich",
    "zombie master",
    "ankh of mishra",
    "tropical island",
    "deathlace",
    "smoke",
    "gaea's liege",
    "island",
    "balance",
    "pirate ship",
    "island sanctuary",
    //
    "gauntlet of might",
    "demonic attorney",
    "howling mine",
    "bayou",
    "fork",
    "goblin king",
    "illusionary mask",
    "living lands",
    "personal incarnation",
    "thoughtlace",
    "mox jet",
    //
    "mana vault",
    "demonic hordes",
    "scrubland",
    "earthquake",
    "helm of chatzuk",
    "verduran enchantress",
    "purelace",
    "kormus bell",
    "copy artifact",
    "clockwork beast",
    "sedge troll",
    //
    "jayemdae tome",
    "island2",
    "nevinyrral's disk",
    "royal assassin",
    "two-headed giant of foriys",
    "plateau",
    "living artifact",
    "time vault",
    "reverse damage",
    "drain power",
    "island2",
    //
    "will-o'-the-wisp",
    "shivan dragon",
    "kudzu",
    "blessing",
    "time walk",
    "nether shadow",
    "rock hydra",
    "fastbond",
    "veteran bodyguard",
    "braingeyser",
    "stasis",
    //
    "mind twist",
    "power surge",
    "web",
    "wrath of god",
    "underground sea",
    "dingus egg",
    "darkpact",
    "wheel of fortune",
    "aspect of wolf",
    "armageddon",
    "timetwister",
];

const limitedUncommonSheet = [
    "swamp3",
    "nettling imp",
    "demonic tutor",
    "mountain2",
    "stone giant",
    "orcish oriflamme",
    "rod of ruin",
    "berserk",
    "library of leng",
    "white knight",
    "black ward",
    // 
    "control magic",
    "feedback",
    "throne of bone",
    "animate dead",
    "wall of bone",
    "swamp",
    "deathgrip",
    "burrowing",
    "living wall",
    "mountain2",
    "keldon warlord",
    //
    "instill energy",
    "thicket basilisk",
    "forest2",
    "castle",
    "ivory cup",
    "plains2",
    "swords to plowshares",
    "lifetap",
    "island3",
    "steal artifact",
    "counterspell",
    //
    "swamp3",
    "sengir vampire",
    "evil presence",
    "earth elemental",
    "mountain",
    "iron star",
    "wall of stone",
    "copper tablet",
    "hurricane",
    "tsunami",
    "forest",
    //
    "lure",
    "obsianus golem",
    "white ward",
    "conversion",
    "plains3",
    "icy manipulator",
    "clone",
    "animate artifact",
    "swamp2",
    "bog wraith",
    "simulacrum",
    //
    "orcish artillery",
    "flashfires",
    "basalt monolith",
    "forest3",
    "wall of ice",
    "ice storm",
    "conservator",
    "serra angel",
    "plains",
    "consecrate land",
    "sol ring",
    //
    "air elemental",
    "island",
    "wall of air",
    "swamp2",
    "gloom",
    "scavenging ghoul",
    "sacrifice",
    "soul net",
    "wall of fire",
    "fire elemental",
    "mountain3",
    //
    "forest",
    "ley druid",
    "regrowth",
    "blue ward",
    "jade statue",
    "plains2",
    "lance",
    "water elemental",
    "wall of water",
    "glasses of urza",
    "uthden troll",
    //
    "tunnel",
    "mountain3",
    "dragon whelp",
    "wooden sphere",
    "forest3",
    "lifeforce",
    "wanderlust",
    "plains",
    "celestial prism",
    "wall of swords",
    "resurrection",
    //
    "red ward",
    "siren's call",
    "phantom monster",
    "black vise",
    "cursed land",
    "black knight",
    "swamp",
    "hypnotic specter",
    "dwarven demolition team",
    "mountain",
    "goblin balloon brigade",
    //
    "camouflage",
    "channel",
    "forest2",
    "wall of brambles",
    "juggernaut",
    "karma",
    "plains3",
    "green ward",
    "crystal rod",
    "phantasmal forces",
    "psionic blast",
];

const limitedCommonSheet = [
    "swamp",
    "howl from beyond",
    "mountain2",
    "lightning bolt",
    "forest2",
    "giant spider",
    "plains3",
    "death ward",
    "unsummon",
    "island3",
    "sea serpent",
    //
    "sinkhole",
    "swamp2",
    "frozen shade",
    "swamp",
    "mountain",
    "shatter",
    "hill giant",
    "war mammoth",
    "wall of wood",
    "forest",
    "giant growth",
    //
    "mountain3",
    "circle of protection: black",
    "benalish hero",
    "plains2",
    "island2",
    "twiddle",
    "power sink",
    "fear",
    "swamp3",
    "plague rats",
    "dark ritual",
    //
    "false orders",
    "mountain2",
    "red elemental blast",
    "ironclaw orcs",
    "llanowar elves",
    "scryb sprites",
    "forest3",
    "plains2",
    "guardian angel",
    "circle of protection: blue",
    "plains3",
    //
    "power leak",
    "prodigal sorcerer",
    "island",
    "jump",
    "unholy strength",
    "drudge skeletons",
    "swamp",
    "mountain",
    "mons's goblin raiders",
    "fireball",
    "mountain3",
    //
    "tranquility",
    "ironroot treefolk",
    "forest",
    "wild growth",
    "plains3",
    "healing salve",
    "circle of protection: red",
    "invisibility",
    "island",
    "island2",
    "creature bond",
    //
    "paralyze",
    "terror",
    "swamp2",
    "scathe zombies",
    "firebreathing",
    "dwarven warriors",
    "mountain",
    "forest3",
    "stream of life",
    "grizzly bears",
    "forest2",
    //
    "holy armor",
    "plains",
    "mesa pegasus",
    "circle of protection: white",
    "spell blast",
    "island",
    "merfolk of the pearl trident",
    "swamp3",
    "pestilence",
    "swamp2",
    "raise dead",
    //
    "mountain3",
    "hurloon minotaur",
    "disintegrate",
    "mountain2",
    "regeneration",
    "forest3",
    "shanodin dryads",
    "pearled unicorn",
    "plains2",
    "disenchant",
    "holy strength",
    //
    "island",
    "phantasmal terrain",
    "blue elemental blast",
    "island2",
    "drain life",
    "swamp3",
    "weakness",
    "earthbind",
    "mountain2",
    "gray ogre",
    "stone rain",
    //
    "fog",
    "forest2",
    "craw wurm",
    "forest",
    "samite healer",
    "plains",
    "circle of protection: green",
    "island3",
    "psychic venom",
    "flight",
    "island3",
];

const arnCommon = [
    "Army of Allah",
    "Flying Men",
    "Hasran Ogress",
    "Hurr Jackal",
    "Metamorphosis",
    "Desert",
    "Piety",
    "Dandân",
    "Hasran Ogress",
    "Desert Nomads",
    "Wyluli Wolf",
    "Giant Tortoise",
    "Cuombajj Witches",
    "Rukh Egg",
    "Nafs Asp",
    "Desert",
    "Moorish Cavalry",
    "Fishliver Oil",
    "Oubliette",
    "Bird Maiden",
    "Sandstorm",
    "War Elephant",
    "Erg Raiders",
    "Kird Ape",
    "Ghazbán Ogre",
    "Desert",
    "Camel",
    "Unstable Mutation",
    "Army of Allah",
    "Flying Men",
    "Stone-Throwing Devils",
    "Hurr Jackal",
    "Metamorphosis",
    "Desert Nomads",
    "Wyluli Wolf",
    "Desert",
    "Piety",
    "Dandân",
    "Hasran Ogress",
    "Rukh Egg",
    "Nafs Asp",
    "Moorish Cavalry",
    "Flying Men",
    "Cuombajj Witches",
    "Sandstorm",
    "Desert",
    "War Elephant",
    "Fishliver Oil",
    "Oubliette",
    "Bird Maiden",
    "Ghazbán Ogre",
    "Camel",
    "Unstable Mutation",
    "Erg Raiders",
    "Kird Ape",
    "Desert",
    "Army of Allah",
    "Flying Men",
    "Stone-Throwing Devils",
    "Hurr Jackal",
    "Metamorphosis",
    "Desert",
    "Piety",
    "Dandân",
    "Hasran Ogress",
    "Mountain",
    "Wyluli Wolf",
    "Giant Tortoise",
    "Cuombajj Witches",
    "Rukh Egg",
    "Nafs Asp",
    "Desert",
    "Moorish Cavalry",
    "Fishliver Oil",
    "Oubliette",
    "Bird Maiden",
    "Nafs Asp",
    "Camel",
    "Erg Raiders",
    "Kird Ape",
    "Ghazbán Ogre",
    "Desert",
    "Camel",
    "Unstable Mutation",
    "Army of Allah",
    "Flying Men",
    "Stone-Throwing Devils",
    "Hurr Jackal",
    "Metamorphosis",
    "Desert Nomads",
    "Wyluli Wolf",
    "Desert",
    "Piety",
    "Dandân",
    "Hasran Ogress",
    "Rukh Egg",
    "Nafs Asp",
    "Moorish Cavalry",
    "Giant Tortoise",
    "Cuombajj Witches",
    "Sandstorm",
    "Desert",
    "War Elephant",
    "Fishliver Oil",
    "Oubliette",
    "Bird Maiden",
    "Ghazbán Ogre",
    "Camel",
    "Unstable Mutation",
    "Erg Raiders",
    "Kird Ape",
    "Moorish Cavalry",
    "Giant Tortoise",
    "Stone-Throwing Devils",
    "Desert Nomads",
    "Wyluli Wolf",
    "War Elephant",
    "Unstable Mutation",
    "Erg Raiders",
    "Kird Ape",
    "Sandstorm",
];

const arnUncommons = [
    "Elephant Graveyard",
    "Abu Ja'far",
    "Brass Man",
    "Merchant Ship",
    "Ring of Ma'rûf",
    "El-Hajjâj",
    "Bottle of Suleiman",
    "Island of Wak-Wak",
    "Mijae Djinn",
    "Erhnam Djinn",
    "Brass Man",
    "King Suleiman",
    "Island of Wak-Wak",
    "Old Man of the Sea",
    "Pyramids",
    "Khabál Ghoul",
    "Aladdin's Ring",
    "Ydwen Efreet",
    "Dancing Scimitar",
    "Elephant Graveyard",
    "Ifh-Bíff Efreet",
    "Abu Ja'far",
    "Shahrazad",
    "Island Fish Jasconius",
    "Bazaar of Baghdad",
    "Sorceress Queen",
    "Flying Carpet",
    "Oasis",
    "Aladdin's Lamp",
    "Magnetic Mountain",
    "Bazaar of Baghdad",
    "Drop of Honey",
    "Merchant Ship",
    "Serendib Efreet",
    "Juzám Djinn",
    "Sindbad",
    "Library of Alexandria",
    "Ali Baba",
    "Sandals of Abdallah",
    "Desert Twister",
    "Eye for an Eye",
    "Sindbad",
    "Jandor's Ring",
    "Eye for an Eye",
    "Repentant Blacksmith",
    "Serendib Djinn",
    "Junún Efreet",
    "Aladdin",
    "City of Brass",
    "Cyclone",
    "City in a Bottle",
    "Khabál Ghoul",
    "Pyramids",
    "Guardian Beast",
    "Ring of Ma'rûf",
    "Jihad",
    "Serendib Efreet",
    "Aladdin's Ring",
    "Guardian Beast",
    "Jeweled Bird",
    "Ali from Cairo",
    "Flying Carpet",
    "Singing Tree",
    "Oasis",
    "Sorceress Queen",
    "Ebony Horse",
    "Abu Ja'far",
    "Aladdin's Lamp",
    "Merchant Ship",
    "Brass Man",
    "El-Hajjâj",
    "Jeweled Bird",
    "Mijae Djinn",
    "Sandals of Abdallah",
    "Erhnam Djinn",
    "Ali from Cairo",
    "Diamond Valley",
    "Bazaar of Baghdad",
    "Old Man of the Sea",
    "Khabál Ghoul",
    "Diamond Valley",
    "Jandor's Saddlebags",
    "Ydwen Efreet",
    "City in a Bottle",
    "Ifh-Bíff Efreet",
    "Magnetic Mountain",
    "Singing Tree",
    "King Suleiman",
    "Shahrazad",
    "Island Fish Jasconius",
    "Oasis",
    "Sorceress Queen",
    "Flying Carpet",
    "Magnetic Mountain",
    "Bottle of Suleiman",
    "Jihad",
    "Ebony Horse",
    "Ali Baba",
    "City of Brass",
    "Eye for an Eye",
    "City of Brass",
    "Sindbad",
    "Sandals of Abdallah",
    "Juzám Djinn",
    "Ali Baba",
    "Desert Twister",
    "Dancing Scimitar",
    "Oasis",
    "Jeweled Bird",
    "Desert Twister",
    "Library of Alexandria",
    "Repentant Blacksmith",
    "Serendib Djinn",
    "Junún Efreet",
    "Aladdin",
    "Library of Alexandria",
    "Cyclone",
    "Jandor's Ring",
    "Cyclone",
    "Jandor's Saddlebags",
    "Drop of Honey",
];

const atqCommons = [
    "Drafna's Restoration",
    "Urza's Mine",
    "Ornithopter",
    "Argivian Blacksmith",
    "Orcish Mechanics",
    "Battering Ram",
    "Artifact Possession",
    "Cursed Rack",
    "Yotian Soldier",
    "Reverse Polarity",
    "Strip Mine2",
    //
    "Clay Statue",
    "Phyrexian Gremlins",
    "Urza's Mine4",
    "Ornithopter",
    "Argivian Blacksmith",
    "Orcish Mechanics",
    "Battering Ram",
    "Artifact Possession",
    "Mishra's Factory2",
    "Staff of Zegon",
    "Reverse Polarity",
    //
    "Atog",
    "Yotian Soldier",
    "Phyrexian Gremlins",
    "Urza's Mine3",
    "Ornithopter",
    "Argivian Blacksmith",
    "Orcish Mechanics",
    "Battering Ram",
    "Artifact Possession",
    "Urza's Power Plant2",
    "Staff of Zegon",
    //
    "Crumble",
    "Artifact Blast",
    "Yotian Soldier",
    "Phyrexian Gremlins",
    "Urza's Mine2",
    "Ornithopter",
    "Argivian Blacksmith",
    "Orcish Mechanics",
    "Clay Statue",
    "Artifact Possession",
    "Feldon's Cane",
    //
    "Tablet of Epityr",
    "Crumble",
    "Artifact Blast",
    "Yotian Soldier",
    "Reconstruction",
    "Urza's Mine3",
    "Grapeshot Catapult",
    "Artifact Ward",
    "Atog",
    "Clay Statue",
    "Phyrexian Gremlins",
    //
    "Urza's Power Plant",
    "Tablet of Epityr",
    "Crumble",
    "Artifact Blast",
    "Urza's Chalice",
    "Reconstruction",
    "Urza's Mine4",
    "Grapeshot Catapult",
    "Reverse Polarity",
    "Atog",
    "Clay Statue",
    //
    "Sage of Lat-Nam",
    "Urza's Tower2",
    "Tablet of Epityr",
    "Crumble",
    "Priest of Yawgmoth",
    "Urza's Chalice",
    "Reconstruction",
    "Urza's Power Plant",
    "Grapeshot Catapult",
    "Argothian Pixies",
    "Atog",
    //
    "Dragon Engine",
    "Sage of Lat-Nam",
    "Urza's Tower3",
    "Tablet of Epityr",
    "Argothian Treefolk",
    "Priest of Yawgmoth",
    "Urza's Chalice",
    "Reconstruction",
    "Urza's Power Plant3",
    "Grapeshot Catapult",
    "Argothian Pixies",
    //
    "Artifact Ward",
    "Dragon Engine",
    "Drafna's Restoration",
    "Urza's Tower4",
    "Amulet of Kroog",
    "Argothian Treefolk",
    "Priest of Yawgmoth",
    "Urza's Chalice",
    "Sage of Lat-Nam",
    "Urza's Power Plant2",
    "Battering Ram",
    //
    "Argothian Pixies",
    "Artifact Ward",
    "Dragon Engine",
    "Drafna's Restoration",
    "Urza's Tower",
    "Amulet of Kroog",
    "Argothian Treefolk",
    "Priest of Yawgmoth",
    "Staff of Zegon",
    "Reverse Polarity",
    "Urza's Power Plant4",
    //
    "Amulet of Kroog",
    "Argothian Pixies",
    "Artifact Ward",
    "Dragon Engine",
    "Drafna's Restoration",
    "Urza's Tower2",
    "Amulet of Kroog",
    "Argothian Treefolk",
    "Artifact Blast",
    "Staff of Zegon",
    "Sage of Lat-Nam",
];

const atqUncommons = [
    "Rakalite",
    "Damping Field",
    "Rocket Launcher",
    "Dwarven Weaponsmith",
    "Armageddon Clock",
    "Powerleech",
    "Onulet",
    "Energy Flux",
    "Ashnod's Transmogrant",
    "Power Artifact",
    "Millstone",
    //
    "Gate to Phyrexia",
    "Mishra's War Machine",
    "Damping Field",
    "Wall of Spears",
    "Shatterstorm",
    "Weakstone",
    "Powerleech",
    "Armageddon Clock",
    "Strip Mine3",
    "Jalum Tome",
    "Power Artifact",
    //
    "Primal Clay",
    "Gate to Phyrexia",
    "Su-Chi",
    "Damping Field",
    "Jalum Tome",
    "Dwarven Weaponsmith",
    "Golgothian Sylex",
    "Mishra's Factory3",
    "Urza's Miter",
    "Strip Mine",
    "Ashnod's Transmogrant",
    //
    "Goblin Artisans",
    "Rakalite",
    "Yawgmoth Demon",
    "Su-Chi",
    "Martyrs of Korlis",
    "Ashnod's Altar",
    "Dwarven Weaponsmith",
    "Obelisk of Undoing",
    "Mishra's Factory",
    "Candelabra of Tawnos",
    "Transmute Artifact",
    //
    "Tetravus",
    "Detonate",
    "Rakalite",
    "Xenic Poltergeist",
    "Su-Chi",
    "Gaea's Avenger",
    "Ashnod's Altar",
    "Goblin Artisans",
    "Colossus of Sardia",
    "Titania's Song",
    "Onulet",
    //
    "Martyrs of Korlis",
    "Mightstone",
    "Detonate",
    "Primal Clay",
    "Xenic Poltergeist",
    "Millstone",
    "Strip Mine4",
    "Urza's Avenger",
    "Goblin Artisans",
    "Onulet",
    "Titania's Song",
    //
    "Ashnod's Battle Gear",
    "Argivian Archaeologist",
    "Mightstone",
    "Detonate",
    "Coral Helm",
    "Xenic Poltergeist",
    "Millstone",
    "Citanul Druid",
    "Triskelion",
    "Ashnod's Battle Gear",
    "Rocket Launcher",
    //
    "Haunting Wind",
    "Tawnos's Weaponry",
    "Martyrs of Korlis",
    "Bronze Tablet",
    "Power Artifact",
    "Tawnos's Wand",
    "Mishra's Workshop",
    "Ashnod's Transmogrant",
    "Citanul Druid",
    "Weakstone",
    "Wall of Spears",
    //
    "Ivory Tower",
    "Haunting Wind",
    "Shapeshifter",
    "Circle of Protection: Artifacts",
    "The Rack",
    "Energy Flux",
    "Tawnos's Wand",
    "Citanul Druid",
    "Tawnos's Coffin",
    "Titania's Song",
    "Rocket Launcher",
    //
    "Transmute Artifact",
    "Ivory Tower",
    "Haunting Wind",
    "The Rack",
    "Circle of Protection: Artifacts",
    "Tawnos's Weaponry",
    "Hurkyl's Recall",
    "Tawnos's Wand",
    "Mishra's Factory4",
    "Clockwork Avian",
    "Powerleech",
    //
    "Mightstone",
    "Transmute Artifact",
    "The Rack",
    "Gate to Phyrexia",
    "Ivory Tower",
    "Circle of Protection: Artifacts",
    "Tawnos's Weaponry",
    "Energy Flux",
    "Primal Clay",
    "Wall of Spears",
    "Weakstone",
];

const lgnCommon = [
    "Zephyr Falcon",
    "Crookshank Kobolds",
    "Durkwood Boars",
    "Divine Offering",
    "Lost Soul",
    "Wall of Earth",
    "Emerald Dragonfly",
    "Tundra Wolves",
    "Glyph of Doom",
    "Boomerang",
    "Wall of Caltrops",
    "Vampire Bats",
    "Flash Counter",
    "Crimson Kobolds",
    "Moss Monster",
    "Indestructible Aura",
    "Energy Tap",
    "Blazing Effigy",
    "Wolverine Pack",
    "Glyph of Life",
    "Ghosts of the Damned",
    "Glyph of Reincarnation",
    "Keepers of the Faith",
    "Wall of Shadows",
    "Flash Flood",
    "Kobolds of Kher Keep",
    "Hornet Cobra",
    "Giant Slug",
    "Devouring Deep",
    "Active Volcano",
    "Cat Warriors",
    "D'Avenant Archer",
    "Venarian Gold",
    "Immolation",
    "Osai Vultures",
    "Walking Dead",
    "Glyph of Delusion",
    "Subdue",
    "Clergy of the Holy Nimbus",
    "Syphon Soul",
    "Remove Soul",
    "Glyph of Destruction",
    "Giant Turtle",
    "Darkness",
    "Aisling Leprechaun",
    "Gaseous Form",
    "Shelkin Brownie",
    "Remove Enchantments",
    "Hell Swarm",
    "Giant Strength",
    "Raging Bull",
    "Transmutation",
    "Enchantment Alteration",
    "Equinox",
    "Wall of Heat",
    "Enchanted Being",
    "Rust",
    "Alabaster Potion",
    "Cyclopean Mummy",
    "Force Spike",
    "Pyrotechnics",
    "Fire Sprites",
    "Amrou Kithkin",
    "Pit Scorpion",
    "Wall of Vapor",
    "Chain Lightning",
    "Spirit Shackle",
    "Wall of Earth",
    "Emerald Dragonfly",
    "Tundra Wolves",
    "Glyph of Doom",
    "Boomerang",
    "Crookshank Kobolds",
    "Durkwood Boars",
    "Divine Offering",
    "Lost Soul",
    "Zephyr Falcon",
    "Psychic Purge",
    "Energy Tap",
    "Blazing Effigy",
    "Wolverine Pack",
    "Glyph of Life",
    "Ghosts of the Damned",
    "Flash Counter",
    "Crimson Kobolds",
    "Moss Monster",
    "Indestructible Aura",
    "Vampire Bats",
    "Feint",
    "Giant Slug",
    "Devouring Deep",
    "Active Volcano",
    "Cat Warriors",
    "D'Avenant Archer",
    "Wall of Shadows",
    "Flash Flood",
    "Kobolds of Kher Keep",
    "Hornet Cobra",
    "Keepers of the Faith",
    "Barbary Apes",
    "Clergy of the Holy Nimbus",
    "Syphon Soul",
    "Remove Soul",
    "Glyph of Destruction",
    "Giant Turtle",
    "Chain Lightning",
    "Avoid Fate",
    "Giant Strength",
    "Holy Day",
    "Anti-Magic Aura",
    "The Brute",
    "Fire Sprites",
    "Amrou Kithkin",
    "Pit Scorpion",
    "Wall of Vapor",
    "Rust",
    "Alabaster Potion",
    "Cyclopean Mummy",
    "Force Spike",
    "Pyrotechnics",
    "Headless Horseman",
];
const lgnUncommon = [
    "Rabid Wombat",
    "Seeker",
    "Seafarer's Quay",
    "Mountain Yeti",
    "Marhault Elsdragon",
    "Heaven's Gate",
    "Eternal Warrior",
    "Hammerheim",
    "Mana Drain",
    "Kry Shield",
    "Wall of Dust",
    "Adventurers' Guildhouse",
    "Takklemaggot",
    "Lord Magnus",
    "Spirit Link",
    "Shimian Night Stalker",
    "Puppet Master",
    "Cocoon",
    "Sir Shandlar of Eberyn",
    "Backdraft",
    "Underworld Dreams",
    "Sivitri Scarzam",
    "Hunding Gjornersen",
    "Frost Giant",
    "Sea Kings' Blessing",
    "Floral Spuzzem",
    "Green Mana Battery",
    "Ramirez DePietro",
    "Wall of Putrid Flesh",
    "Silhouette",
    "Blue Mana Battery",
    "Unholy Citadel",
    "Presence of the Master",
    "Deadfall",
    "Relic Barrier",
    "Land Tax",
    "Tor Wauki",
    "Spectral Cloak",
    "Wall of Tombstones",
    "Cathedral of Serra",
    "Ivory Guardians",
    "Radjan Spirit",
    "Princess Lucrezia",
    "Brine Hag",
    "White Mana Battery",
    "Relic Bind",
    "Arboria",
    "Great Defender",
    "Sylvan Library",
    "Relic Barrier",
    "Pradesh Gypsies",
    "Sunastian Falconer",
    "Undertow",
    "Wall of Light",
    "Blight",
    "Aerathi Berserker",
    "Kasimir the Lone Wolf",
    "Touch of Darkness",
    "Azure Drake",
    "Storm Seeker",
    "Tolaria",
    "Life Chisel",
    "Primordial Ooze",
    "Quagmire",
    "Pendelhaven",
    "Life Chisel",
    "Urborg",
    "Backfire",
    "Lady Orca",
    "Red Mana Battery",
    "Demonic Torment",
    "The Lady of the Mountain",
    "Untamed Wilds",
    "Karakas",
    "Great Wall",
    "Barktooth Warbeard",
    "Whirling Dervish",
    "Pavel Maliki",
    "Evil Eye of Orms-by-Gore",
    "Greater Realm of Preservation",
    "Blood Lust",
    "Reset",
    "Fortified Area",
    "Crevasse",
    "Jerrard of the Closed Fist",
    "Segovian Leviathan",
    "Fallen Angel",
    "Dwarven Song",
    "Shield Wall",
    "Beasts of Bogardan",
    "Ichneumon Druid",
    "Hammerheim",
    "Righteous Avengers",
    "Horror of Horrors",
    "Tolaria",
    "Kismet",
    "Reincarnation",
    "Black Mana Battery",
    "Pendelhaven",
    "Kobold Taskmaster",
    "Urborg",
    "Winds of Change",
    "Torsten Von Ursus",
    "Kobold Drill Sergeant",
    "Part Water",
    "Jasmine Boreal",
    "Hyperion Blacksmith",
    "Karakas",
    "Dream Coat",
    "Riven Turnbull",
    "Wall of Wonder",
    "Jedit Ojanen",
    "Abomination",
    "Sylvan Paradise",
    "Mountain Stronghold",
    "Marble Priest",
    "Craw Giant",
    "Infernal Medusa",
    "Tobias Andrion",
    "Visions",
    "Lesser Werewolf",
];

const drkCommon = [
    "Water Wurm",
    "Savaen Elves",
    "Marsh Gas",
    "Fissure",
    "Dust to Dust",
    "Drowned",
    "Land Leeches",
    "Bog Rats",
    "Goblin Rock Sled",
    "Miracle Worker",
    "Sunken City",
    "Murk Dwellers",
    "Goblins of the Flarg",
    "Squire",
    "Giant Shark",
    "Scavenger Folk",
    "Bog Imp",
    "Goblin Digging Team",
    "Brainwash",
    "Riptide",
    "Dark Heart of the Wood",
    "Marsh Goblins",
    "Pikemen",
    "Ashes to Ashes",
    "Carnivorous Plant",
    "Festival",
    "Erosion",
    "Holy Light",
    "Gaea's Touch",
    "Giant Shark",
    "Dust to Dust",
    "Word of Binding",
    "Scarwood Goblins",
    "Goblin Caves",
    "Venom",
    "Deep Water",
    "Word of Binding",
    "Goblin Hero",
    "Dark Heart of the Wood",
    "Marsh Goblins",
    "Fissure",
    "Scavenger Folk",
    "Erosion",
    "Festival",
    "Ghost Ship",
    "Morale",
    "Goblin Shrine",
    "Gaea's Touch",
    "Murk Dwellers",
    "Scarwood Goblins",
    "Sunken City",
    "Miracle Worker",
    "Marsh Gas",
    "Goblin Hero",
    "Carnivorous Plant",
    "Marsh Viper",
    "Inquisition",
    "Holy Light",
    "Goblin Digging Team",
    "Savaen Elves",
    "Water Wurm",
    "Morale",
    "Goblin Shrine",
    "Land Leeches",
    "Brainwash",
    "Riptide",
    "Dust to Dust",
    "Scavenger Folk",
    "Bog Imp",
    "Drowned",
    "Goblins of the Flarg",
    "Squire",
    "Inquisition",
    "Marsh Viper",
    "Ghost Ship",
    "Bog Rats",
    "Goblin Rock Sled",
    "Marsh Gas",
    "Fissure",
    "Venom",
    "Ashes to Ashes",
    "Miracle Worker",
    "Sunken City",
    "Holy Light",
    "Bog Imp",
    "Goblin Digging Team",
    "Savaen Elves",
    "Squire",
    "Giant Shark",
    "Pikemen",
    "Goblin Caves",
    "Deep Water",
    "Dark Heart of the Wood",
    "Marsh Goblins",
    "Scarwood Goblins",
    "Drowned",
    "Gaea's Touch",
    "Goblins of the Flarg",
    "Murk Dwellers",
    "Festival",
    "Goblin Hero",
    "Land Leeches",
    "Goblin Rock Sled",
    "Bog Rats",
    "Venom",
    "Deep Water",
    "Goblin Caves",
    "Inquisition",
    "Morale",
    "Water Wurm",
    "Carnivorous Plant",
    "Word of Binding",
    "Erosion",
    "Brainwash",
    "Riptide",
    "Maze of Ith",
    "Ashes to Ashes",
    "Pikemen",
    "Marsh Viper",
    "Ghost Ship",
    "Goblin Shrine",
];
const drkUncommon = [
    "Dance of Many",
    "Curse Artifact",
    "Reflecting Mirror",
    "Mana Clash",
    "Tormod's Crypt",
    "Sisters of the Flame",
    "Dark Sphere",
    "Blood Moon",
    "Necropolis",
    "The Fallen",
    "Apprentice Wizard",
    "Fire and Brimstone",
    "Scarwood Hag",
    "Mind Bomb",
    "Runesword",
    "Whippoorwill",
    "Martyr's Cry",
    "Fountain of Youth",
    "War Barge",
    "Spitting Slug",
    "Cave People",
    "Eater of the Dead",
    "Living Armor",
    "Niall Silvain",
    "Scarecrow",
    "Tangle Kelp",
    "Barl's Cage",
    "Fellwar Stone",
    "Worms of the Earth",
    "Eater of the Dead",
    "Amnesia",
    "Lurker",
    "Necropolis",
    "Uncle Istvan",
    "Tivadar's Crusade",
    "Banshee",
    "Cleansing",
    "Amnesia",
    "The Fallen",
    "Elves of Deep Shadow",
    "Witch Hunter",
    "Coal Golem",
    "Merfolk Assassin",
    "Elves of Deep Shadow",
    "City of Shadows",
    "Wand of Ith",
    "Leviathan",
    "Fire Drake",
    "Fasting",
    "Tracker",
    "Uncle Istvan",
    "Orc General",
    "Psychic Allergy",
    "Banshee",
    "Inferno",
    "Fountain of Youth",
    "Ball Lightning",
    "Runesword",
    "Fire and Brimstone",
    "Grave Robbers",
    "Diabolic Machine",
    "Tivadar's Crusade",
    "Mana Vortex",
    "War Barge",
    "Blood of the Martyr",
    "Spitting Slug",
    "Orc General",
    "Book of Rass",
    "Sorrow's Path",
    "Scarwood Hag",
    "Bone Flute",
    "Electric Eel",
    "Reflecting Mirror",
    "Angry Mob",
    "Sisters of the Flame",
    "Exorcist",
    "Standing Stones",
    "Scarwood Bandits",
    "Tangle Kelp",
    "Diabolic Machine",
    "Goblin Wizard",
    "Angry Mob",
    "Preacher",
    "Brothers of Fire",
    "Tower of Coireall",
    "Electric Eel",
    "Fellwar Stone",
    "Rag Man",
    "Tower of Coireall",
    "Blood of the Martyr",
    "Whippoorwill",
    "Curse Artifact",
    "Nameless Race",
    "People of the Woods",
    "Tormod's Crypt",
    "Season of the Witch",
    "Book of Rass",
    "Wormwood Treefolk",
    "Brothers of Fire",
    "Flood",
    "Eternal Flame",
    "Wand of Ith",
    "Hidden Path",
    "Skull of Orm",
    "Cave People",
    "Frankenstein's Monster",
    "Flood",
    "Standing Stones",
    "Bone Flute",
    "Scarecrow",
    "People of the Woods",
    "Fasting",
    "Fire Drake",
    "Dark Sphere",
    "Safe Haven",
    "Merfolk Assassin",
    "Coal Golem",
    "Living Armor",
    "Stone Calendar",
    "Skull of Orm",
    "Knights of Thorn",
];

const femCommon = [
    "Mindstab Thrull (C)",
    "Icatian Moneychanger (C)",
    "Elvish Scout (C)",
    "Farrel's Zealot (C)",
    "Orcish Spy (B)",
    "Basal Thrull (B)",
    "Merseine (D)",
    "Combat Medic (B)",
    "Dwarven Soldier (A)",
    "Icatian Scout (C)",
    "Goblin War Drums (C)",
    "Spore Cloud (A)",
    "High Tide (C)",
    "Necrite (C)",
    "Homarid Warrior (C)",
    "Delif's Cone",
    "Thallid (B)",
    "Brassclaw Orcs (C)",
    "Hymn to Tourach (D)",
    "Thorn Thallid (C)",
    "Armor Thrull (B)",
    "Homarid (C)",
    "Icatian Javelineers (C)",
    "Dwarven Soldier (C)",
    "Order of Leitbur (C)",
    "Goblin Chirurgeon (B)",
    "Combat Medic (D)",
    "Homarid (D)",
    "Icatian Infantry (C)",
    "Orcish Veteran (C)",
    "Vodalian Soldiers (C)",
    "Goblin Grenade (A)",
    "Icatian Moneychanger (B)",
    "Thallid (C)",
    "Merseine (C)",
    "Elvish Hunter (A)",
    "Vodalian Soldiers (D)",
    "Thorn Thallid (D)",
    "Armor Thrull (A)",
    "Elven Fortress (D)",
    "Order of the Ebon Hand (C)",
    "Farrel's Zealot (B)",
    "Initiates of the Ebon Hand (B)",
    "Night Soil (C)",
    "Orcish Veteran (A)",
    "Basal Thrull (D)",
    "Icatian Infantry (D)",
    "Brassclaw Orcs (A)",
    "Hymn to Tourach (C)",
    "Icatian Scout (B)",
    "Goblin War Drums (D)",
    "Orcish Spy (C)",
    "Elvish Scout (A)",
    "Vodalian Mage (A)",
    "Tidal Flats (C)",
    "High Tide (A)",
    "Dwarven Soldier (B)",
    "Spore Cloud (B)",
    "Homarid Warrior (A)",
    "Necrite (A)",
    "Icatian Infantry (A)",
    "Brassclaw Orcs (D)",
    "Vodalian Soldiers (A)",
    "Hymn to Tourach (B)",
    "Goblin War Drums (A)",
    "Icatian Scout (A)",
    "Elven Fortress (A)",
    "Icatian Javelineers (A)",
    "Mindstab Thrull (A)",
    "Goblin Chirurgeon (C)",
    "Elvish Hunter (C)",
    "Merseine (A)",
    "Basal Thrull (A)",
    "Combat Medic (C)",
    "Thorn Thallid (A)",
    "Homarid (A)",
    "Armor Thrull (C)",
    "Vodalian Soldiers (B)",
    "Brassclaw Orcs (B)",
    "Thorn Thallid (B)",
    "Homarid (B)",
    "Order of Leitbur (A)",
    "Orcish Veteran (D)",
    "Thallid (A)",
    "Vodalian Mage (B)",
    "Order of the Ebon Hand (B)",
    "Icatian Infantry (B)",
    "Orcish Veteran (B)",
    "Basal Thrull (C)",
    "Combat Medic (A)",
    "Hymn to Tourach (A)",
    "Goblin War Drums (B)",
    "Armor Thrull (D)",
    "Initiates of the Ebon Hand (A)",
    "Farrel's Zealot (A)",
    "Orcish Spy (A)",
    "Elvish Scout (B)",
    "Merseine (B)",
    "Thallid (D)",
    "Goblin Chirurgeon (A)",
    "Tidal Flats (B)",
    "Night Soil (A)",
    "Icatian Scout (D)",
    "Elven Fortress (C)",
    "Night Soil (B)",
    "Tidal Flats (A)",
    "Mindstab Thrull (B)",
    "Icatian Javelineers (B)",
    "Necrite (B)",
    "Order of Leitbur (B)",
    "Elvish Hunter (B)",
    "Initiates of the Ebon Hand (C)",
    "Goblin Grenade (C)",
    "Order of the Ebon Hand (A)",
    "Vodalian Mage (C)",
    "Icatian Moneychanger (A)",
    "Goblin Grenade (B)",
    "Spore Cloud (C)",
    "High Tide (B)",
    "Elven Fortress (B)",
    "Homarid Warrior (B)",
];
const femUncommon = [
    "Farrelite Priest",
    "Ebon Praetor",
    "Orcish Captain",
    "Spirit Shield",
    "Thrull Retainer",
    "Conch Horn",
    "Sand Silos",
    "Deep Spawn",
    "Icatian Lieutenant",
    "Spore Flower",
    "Zelyon Sword",
    "Raiding Party",
    "Dwarven Ruins",
    "Heroism",
    "Thelonite Druid",
    "Farrel's Mantle",
    "Tidal Influence",
    "Soul Exchange",
    "Feral Thallid",
    "Svyelunite Temple",
    "Goblin Kites",
    "Homarid Spawning Bed",
    "Homarid Shaman",
    "Thelon's Chant",
    "Dwarven Hold",
    "Svyelunite Priest",
    "Thelonite Monk",
    "Hand of Justice",
    "Dwarven Lieutenant",
    "Ring of Renewal",
    "Tourach's Chant",
    "Thrull Champion",
    "Icatian Priest",
    "Thrull Retainer",
    "Farrelite Priest",
    "Raiding Party",
    "Farrel's Mantle",
    "Ebon Stronghold",
    "Homarid Spawning Bed",
    "Breeding Pit",
    "Spore Flower",
    "Deep Spawn",
    "Ruins of Trokair",
    "Orcish Captain",
    "Seasinger",
    "Aeolipile",
    "Thrull Wizard",
    "Balm of Restoration",
    "Dwarven Catapult",
    "Thelonite Druid",
    "Orgg",
    "Icatian Phalanx",
    "Hollow Trees",
    "Thallid Devourer",
    "Draconian Cylix",
    "Derelor",
    "Thelon's Chant",
    "Dwarven Armorer",
    "Svyelunite Priest",
    "Rainbow Vale",
    "Icatian Town",
    "Dwarven Lieutenant",
    "Vodalian War Machine",
    "Tourach's Chant",
    "Fungal Bloom",
    "Icatian Priest",
    "Thrull Wizard",
    "Icatian Phalanx",
    "Havenwood Battleground",
    "Thallid Devourer",
    "Goblin Kites",
    "Tidal Influence",
    "Feral Thallid",
    "Heroism",
    "Dwarven Ruins",
    "Seasinger",
    "Dwarven Catapult",
    "Orcish Captain",
    "Elvish Farmer",
    "Thrull Retainer",
    "Tourach's Gate",
    "Farrelite Priest",
    "Soul Exchange",
    "Elven Lyre",
    "Deep Spawn",
    "Goblin Warrens",
    "Spore Flower",
    "Icatian Skirmishers",
    "Homarid Spawning Bed",
    "Implements of Sacrifice",
    "Breeding Pit",
    "Havenwood Battleground",
    "Thrull Wizard",
    "Farrel's Mantle",
    "Thelonite Druid",
    "Breeding Pit",
    "Bottomless Vault",
    "Raiding Party",
    "Svyelunite Temple",
    "Delif's Cube",
    "Thelon's Chant",
    "Goblin Flotilla",
    "Svyelunite Priest",
    "Thelon's Curse",
    "River Merfolk",
    "Dwarven Lieutenant",
    "Icatian Store",
    "Tourach's Chant",
    "Vodalian Knights",
    "Icatian Priest",
    "Goblin Kites",
    "Tidal Influence",
    "Ruins of Trokair",
    "Soul Exchange",
    "Heroism",
    "Feral Thallid",
    "Icatian Phalanx",
    "Thallid Devourer",
    "Dwarven Catapult",
    "Ebon Stronghold",
    "Seasinger",
];

export const uncutSheets = [
    limitedRareSheet,
    limitedUncommonSheet,
    limitedCommonSheet,
]