// Data from https://www.lethe.xyz/mtg/collation/2ed.html
const limitedRareSheet = [
    "winter orb",
    "nightmare",
    "jade monolith",
    "manabarbs",
    "mox emerald",
    "elvish archers",
    "sunglasses of urza",
    "animate wall",
    "tundra",
    "sleight of mind",
    "chaos orb",
    //
    "lifelace",
    "savannah",
    "righteousness",
    "ancestral recall",
    "black lotus",
    "bad moon",
    "mox sapphire",
    "raging river",
    "fungusaur",
    "northern paladin",
    "magical hack",
    //
    "cockatrice",
    "mox ruby",
    "blaze of glory",
    "disrupting scepter",
    "lord of the pit",
    "mana flare",
    "taiga",
    "natural selection",
    "crusade",
    "mana short",
    "birds of paradise",
    //
    "cyclopean tomb",
    "contract from below",
    "badlands",
    "granite gargoyle",
    "mox pearl",
    "timber wolves",
    "meekstone",
    "savannah lions",
    "vesuvan doppelganger",
    "word of command",
    "forcefield",
    //
    "chaoslace",
    "the hive",
    "lord of atlantis",
    "warp artifact",
    "roc of kher ridges",
    "force of nature",
    "farmstead",
    "mahamoti djinn",
    "volcanic island",
    "volcanic eruption",
    "island",
    //
    "lich",
    "zombie master",
    "ankh of mishra",
    "tropical island",
    "deathlace",
    "smoke",
    "gaea's liege",
    "island",
    "balance",
    "pirate ship",
    "island sanctuary",
    //
    "gauntlet of might",
    "demonic attorney",
    "howling mine",
    "bayou",
    "fork",
    "goblin king",
    "illusionary mask",
    "living lands",
    "personal incarnation",
    "thoughtlace",
    "mox jet",
    //
    "mana vault",
    "demonic hordes",
    "scrubland",
    "earthquake",
    "helm of chatzuk",
    "verduran enchantress",
    "purelace",
    "kormus bell",
    "copy artifact",
    "clockwork beast",
    "sedge troll",
    //
    "jayemdae tome",
    "island2",
    "nevinyrral's disk",
    "royal assassin",
    "two-headed giant of foriys",
    "plateau",
    "living artifact",
    "time vault",
    "reverse damage",
    "drain power",
    "island2",
    //
    "will-o'-the-wisp",
    "shivan dragon",
    "kudzu",
    "blessing",
    "time walk",
    "nether shadow",
    "rock hydra",
    "fastbond",
    "veteran bodyguard",
    "braingeyser",
    "stasis",
    //
    "mind twist",
    "power surge",
    "web",
    "wrath of god",
    "underground sea",
    "dingus egg",
    "darkpact",
    "wheel of fortune",
    "aspect of wolf",
    "armageddon",
    "timetwister",
];

const limitedUncommonSheet = [
    "swamp3",
    "nettling imp",
    "demonic tutor",
    "mountain2",
    "stone giant",
    "orcish oriflamme",
    "rod of ruin",
    "berserk",
    "library of leng",
    "white knight",
    "black ward",
    // 
    "control magic",
    "feedback",
    "throne of bone",
    "animate dead",
    "wall of bone",
    "swamp",
    "deathgrip",
    "burrowing",
    "living wall",
    "mountain2",
    "keldon warlord",
    //
    "instill energy",
    "thicket basilisk",
    "forest2",
    "castle",
    "ivory cup",
    "plains2",
    "swords to plowshares",
    "lifetap",
    "island3",
    "steal artifact",
    "counterspell",
    //
    "swamp3",
    "sengir vampire",
    "evil presence",
    "earth elemental",
    "mountain",
    "iron star",
    "wall of stone",
    "copper tablet",
    "hurricane",
    "tsunami",
    "forest",
    //
    "lure",
    "obsianus golem",
    "white ward",
    "conversion",
    "plains3",
    "icy manipulator",
    "clone",
    "animate artifact",
    "swamp2",
    "bog wraith",
    "simulacrum",
    //
    "orcish artillery",
    "flashfires",
    "basalt monolith",
    "forest3",
    "wall of ice",
    "ice storm",
    "conservator",
    "serra angel",
    "plains",
    "consecrate land",
    "sol ring",
    //
    "air elemental",
    "island",
    "wall of air",
    "swamp2",
    "gloom",
    "scavenging ghoul",
    "sacrifice",
    "soul net",
    "wall of fire",
    "fire elemental",
    "mountain3",
    //
    "forest",
    "ley druid",
    "regrowth",
    "blue ward",
    "jade statue",
    "plains2",
    "lance",
    "water elemental",
    "wall of water",
    "glasses of urza",
    "uthden troll",
    //
    "tunnel",
    "mountain3",
    "dragon whelp",
    "wooden sphere",
    "forest3",
    "lifeforce",
    "wanderlust",
    "plains",
    "celestial prism",
    "wall of swords",
    "resurrection",
    //
    "red ward",
    "siren's call",
    "phantom monster",
    "black vise",
    "cursed land",
    "black knight",
    "swamp",
    "hypnotic specter",
    "dwarven demolition team",
    "mountain",
    "goblin balloon brigade",
    //
    "camouflage",
    "channel",
    "forest2",
    "wall of brambles",
    "juggernaut",
    "karma",
    "plains3",
    "green ward",
    "crystal rod",
    "phantasmal forces",
    "psionic blast",
];

const limitedCommonSheet = [
    "swamp",
    "howl from beyond",
    "mountain2",
    "lightning bolt",
    "forest2",
    "giant spider",
    "plains3",
    "death ward",
    "unsummon",
    "island3",
    "sea serpent",
    //
    "sinkhole",
    "swamp2",
    "frozen shade",
    "swamp",
    "mountain",
    "shatter",
    "hill giant",
    "war mammoth",
    "wall of wood",
    "forest",
    "giant growth",
    //
    "mountain3",
    "circle of protection: black",
    "benalish hero",
    "plains2",
    "island2",
    "twiddle",
    "power sink",
    "fear",
    "swamp3",
    "plague rats",
    "dark ritual",
    //
    "false orders",
    "mountain2",
    "red elemental blast",
    "ironclaw orcs",
    "llanowar elves",
    "scryb sprites",
    "forest3",
    "plains2",
    "guardian angel",
    "circle of protection: blue",
    "plains3",
    //
    "power leak",
    "prodigal sorcerer",
    "island",
    "jump",
    "unholy strength",
    "drudge skeletons",
    "swamp",
    "mountain",
    "mons's goblin raiders",
    "fireball",
    "mountain3",
    //
    "tranquility",
    "ironroot treefolk",
    "forest",
    "wild growth",
    "plains3",
    "healing salve",
    "circle of protection: red",
    "invisibility",
    "island",
    "island2",
    "creature bond",
    //
    "paralyze",
    "terror",
    "swamp2",
    "scathe zombies",
    "firebreathing",
    "dwarven warriors",
    "mountain",
    "forest3",
    "stream of life",
    "grizzly bears",
    "forest2",
    //
    "holy armor",
    "plains",
    "mesa pegasus",
    "circle of protection: white",
    "spell blast",
    "island",
    "merfolk of the pearl trident",
    "swamp3",
    "pestilence",
    "swamp2",
    "raise dead",
    //
    "mountain3",
    "hurloon minotaur",
    "disintegrate",
    "mountain2",
    "regeneration",
    "forest3",
    "shanodin dryads",
    "pearled unicorn",
    "plains2",
    "disenchant",
    "holy strength",
    //
    "island",
    "phantasmal terrain",
    "blue elemental blast",
    "island2",
    "drain life",
    "swamp3",
    "weakness",
    "earthbind",
    "mountain2",
    "gray ogre",
    "stone rain",
    //
    "fog",
    "forest2",
    "craw wurm",
    "forest",
    "samite healer",
    "plains",
    "circle of protection: green",
    "island3",
    "psychic venom",
    "flight",
    "island3",
];


export const uncutSheets = [
    limitedRareSheet,
    limitedUncommonSheet,
    limitedCommonSheet,
]